---
dist: trusty
sudo: false

language: php

php:
  - 5.6
  - 7.0

addons:
  apt:
    sources:
    - sourceline: 'ppa:mike42/mdcheckr'
    packages:
    - mdcheckr

install:
  - composer install

before_script:
  - printf "\n" | pecl install imagick

script:
  # Check all PHP files with phpcs. Does not fail test.
  - php vendor/bin/phpcs --standard=psr2 --ignore=vendor -n .
  # Check all *.md files in git with mdcheckr
  - git ls-files | grep '\.md$' | tr '\n' '\0' | xargs -0 mdcheckr
  # Execute unit tests
  - php vendor/bin/phpunit

